update script to check for bad values

diff --git a/.ci/all.yml b/.ci/all.yml
--- a/.ci/all.yml
+++ b/.ci/all.yml
@@ -144,20 +144,26 @@ steps:
         IFS='%';
         read -rasplitIFS<<< "$str"
         cur=${splitIFS[0]}
-        IFS=' ';
-        echo "$timestamp ${splitIFS[0]}" >> docs/tarpaulin_summary.txt
-        cp README.md.template README.md
-        export ccvalue=${splitIFS[0]}
-        perl -pi -e 's/CODECOVERAGE/$ENV{ccvalue}/g' README.md
-        chmod 755 ./.ci/make_cc_graph.sh
-        ./.ci/make_cc_graph.sh
+        re='^[0-9]+([.][0-9]+)?$'
+        if ! [[ $cur =~ $re ]] ; then
+          echo "error: Not a number" >&2; exit 1
+        else
+          echo "number ok $cur"
+          IFS=' ';
+          echo "$timestamp ${splitIFS[0]}" >> docs/tarpaulin_summary.txt
+          cp README.md.template README.md
+          export ccvalue=${splitIFS[0]}
+          perl -pi -e 's/CODECOVERAGE/$ENV{ccvalue}/g' README.md
+          chmod 755 ./.ci/make_cc_graph.sh
+          ./.ci/make_cc_graph.sh
 
-        git config --global user.email "pipelinesbot.noreply@example.com"
-        git config --global user.name "Pipelines-Bot"
-        git pull
-        git add --all
-        git commit -m"Pipelines-Bot: Updated repo (via tarpaulin script) Source Version is $(Build.SourceVersion)";
-        git push https://$(github_pat)@github.com/cgilliard/bitcoinmw.git
+          git config --global user.email "pipelinesbot.noreply@example.com"
+          git config --global user.name "Pipelines-Bot"
+          git pull
+          git add --all
+          git commit -m"Pipelines-Bot: Updated repo (via tarpaulin script) Source Version is $(Build.SourceVersion)";
+          git push https://$(github_pat)@github.com/cgilliard/bitcoinmw.git
+        fi
       else
         echo "not updating too recent"
       fi
